font_family FiraCode Nerd Font
font_size 10.0

wayland_titlebar_color #404040
background #303030

cursor #bbbbbb
cursor_text_color #000000

cursor_trail 3
cursor_trail_decay 0.1 0.3

remember_window_size no
initial_window_width 100c
initial_window_height 30c
resize_in_steps yes
map shift+enter send_text all \e\r
